//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "games")]
pub struct Model {
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_name = "gameDir", column_type = "Text", nullable)]
    pub game_dir: Option<String>,
    #[sea_orm(column_name = "saveDir", column_type = "Text", nullable)]
    pub save_dir: Option<String>,
    #[sea_orm(column_name = "exePath", column_type = "Text", nullable)]
    pub exe_path: Option<String>,
    #[sea_orm(column_type = "custom(\"INTEGER UNSIGNED\")", nullable)]
    pub state: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub uuid: Option<String>,
    #[sea_orm(column_name = "updateTime")]
    pub update_time: Option<Decimal>,
    pub order: Option<Decimal>,
    #[sea_orm(column_name = "nativeSaveNumber")]
    pub native_save_number: Option<Decimal>,
    #[sea_orm(
        column_name = "startWithStrategy",
        column_type = "custom(\"INTEGER UNSIGNED\")",
        nullable
    )]
    pub start_with_strategy: Option<i32>,
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
